# fly.toml app configuration file generated for rough-breeze-8004 on 2023-08-06T19:59:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-breeze-8004"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  protocol = "http"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
